# After taking the required subscriptions(azure cognitive services and azure openAI) you can enter the keys below to succesfully run this code
openAIKey=""
language=""
region=""
speechKey=""
engine=""
OpenAI_version=""
OpenAI_base=""
OpenAI_type=""
storage_account_key = ""
storage_account_name = ""
connection_string = ""
container_name = ""
path=""